name: Build and Deploy

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Choose the Node.js version you want

    - name: Install dependencies
      run: |
        npm install
        mkdir -p dist
        mv node_modules dist/

    - name: Build your project (replace with your build command)
      working-directory: dist
      run: |
        # Replace this with your build command, for example:
        npm run build
        echo "Build your project here"

    - name: Deploy to GitHub Pages (replace with your deployment method)
      run: |
        # Replace this with your deployment command, for example:
        gh-pages -d dist
        echo "Deploy your project to GitHub Pages or other hosting here"
